apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/configmap.yaml

  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml

  - dbapp/deployment.yaml
  - dbapp/service.yaml

  - front/deployment.yaml
  - front/service.yaml

  - ingress/ingress.yaml
