# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes / No'), ('date', 'Date'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=255)),
                ('fqdn', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('sql_server', 'SQL Server'), ('oracle', 'Oracle'), ('mysql', 'MySQL'), ('azure_sql', 'Azure SQL'), ('weblogic', 'Oracle WebLogic'), ('zen', 'ZEN'), ('other', 'Other')], default='other', max_length=30)),
                ('dbms', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('internal_version', models.CharField(blank=True, max_length=100)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(blank=True, max_length=100)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='In Use', max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=255)),
                ('architecture', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('network', models.CharField(blank=True, max_length=255)),
                ('resource_type', models.CharField(blank=True, max_length=255)),
                ('resource_group', models.CharField(blank=True, max_length=255)),
                ('subscription', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['server_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=255)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='inventory.databaseasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.customfielddefinition')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='inventory.databaseasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'field'), name='unique_asset_custom_field')],
            },
        ),
    ]
