apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbapp
spec:
  replicas: 1

  selector:
    matchLabels:
      app: dbapp

  template:
    metadata:
      labels:
        app: dbapp

    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      imagePullSecrets:
        - name: dockerhub-regcred

      containers:
        - name: dbapp
          image: devops-dbinventory-dbapp
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL

          envFrom:
            - configMapRef:
                name: dbinventory-config

          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dbinventory-secret
                  key: DJANGO_SECRET_KEY

            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbinventory-secret
                  key: SQL_PASSWORD

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /api/v1/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: dbapp
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/v1/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: dbapp
            initialDelaySeconds: 30
            periodSeconds: 20
